name: CI
on: [push]

jobs:
  build:
    name: XXX
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build docker image
      run: docker build -t ${{ github.repository }}:latest .
    - name: Publish docker image
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker push ${{ github.repository }}:latest
        docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
        docker tag ${{ github.repository }}:latest docker.pkg.github.com/${{ github.repository }}/amazonlinux-reproducible:latest
        docker push docker.pkg.github.com/${{ github.repository }}/amazonlinux-reproducible:latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
