name: CI
on: [push]

jobs:
  build:
    name: XXX
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build docker image
      run: docker build -t ${{ github.repository }}:latest .
    - name: Login to registry
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish docker image
      run: docker push ${{ github.repository }}:latest
