name: CI
on: [push]

jobs:
  build:
    name: XXX
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build docker image
      run: docker build -t ${{ github.repository }}:latest .
